version: '2'
services:
    flask:
        build: ./flask
        container_name: flask
        command: python /app/app.py
        privileged: true
        restart: always
        volumes:
            - $PWD/flask:/app
        ports:
            - 8080

    nginx:
        image: nginx
        container_name: nginx
        command: [nginx, '-g', 'daemon off;']
        privileged: true
        restart: always
        volumes:
            - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80
